### ISSUE TITLE
README bug in "Add listener in event on"

### ISSUE THREAD

**Issue by phoe** [noloop/eventbus#1]
https://github.com/noloop/eventbus#add-listener-in-event-on

> Add listener in event on

> An once event is an event that can only be emitted once because the added listener is deleted after it is first emitted.

I do not think this paragraph is intended. It seems like a copypaste from above.

**Comment by noloop** [comment]
My bad. Lack of attention, It's done: https://github.com/noloop/eventbus/commit/9058b4efcdfccbbc8189647bdce5c324897e0da0
